project:
  type: book
  output-dir: Output

book:
  title: "A Living Handbook on EstimandsOu"
  author: "Core Clinical Sciences"
  # logo: X
  # repo-url: X
  # repo-branch: main
  # repo-actions: [issue]
  
  chapters:
      - index.qmd
      - part: Intro to Estimands
        chapters: 
            - Chapters/1-Estimands-Laymans-Terms.qmd

      # - part: Appendices
      #   chapters: 
      #       - Chapters/Appendix-1-Codes.qmd

# bibliography: references.bib

number-depth: 3 

format:
  html:
    theme: cosmo
    code-link: true