project:
  type: book
  output-dir: Output

csl: nature.csl
link-citations: true

book:
  title: "A Living Handbook on Estimands"
  author: "Core Clinical Sciences"
  repo-url: "https://github.com/CoreClinicalSciences/Estimands-Handbook"
  repo-actions: [issue]
  chapters:
    - index.qmd
    
    - part: Foundations
    - Chapters/Estimands-Laymans-Terms.qmd
    
    - part: Core Framework
    - Chapters/Core-Framework.qmd
    
    - part: Statistical Methods and Analysis
    - Chapters/Estimands-and-Causal-Inference.qmd
    - Chapters/Time-to-Event-Analysis-and-Estimands.qmd


number-depth: 3
format:
  html:
    theme: cosmo
    code-link: true
